# Generated by Django 6.0.4 on 2026-07-22 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مشرف عام'), ('teacher', 'معلم/شيخ'), ('student', 'طالب'), ('parent', 'ولي أمر')], default='teacher', max_length=20, verbose_name='الدور/الصلاحية')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
