# Generated by Django 6.0.4 on 2026-07-22 22:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحلقة')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='اسم المعلم')),
                ('level', models.CharField(choices=[('memorization', 'حفظ ومراجعة'), ('tajweed', 'قراءة وتجويد'), ('alphabets', 'قراءة وكتابة')], default='memorization', max_length=20, verbose_name='المستوى')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('behavior_rating', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='تقييم السلوك')),
                ('completed_juz', models.JSONField(default=list, verbose_name='الأجزاء المجتازة')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)], verbose_name='العمر')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('newStudent', 'مستجد'), ('suspended', 'موقوف'), ('graduated', 'خريج')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='halaqat.circle', verbose_name='الحلقة')),
            ],
        ),
        migrations.CreateModel(
            name='MemorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التسجيل')),
                ('type', models.CharField(choices=[('memorization', 'حفظ جديد'), ('revision', 'مراجعة'), ('recitation', 'تلاوة'), ('alphabets', 'تهجي وقراءة')], max_length=20)),
                ('surah_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_verse', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('to_verse', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('lesson_name', models.CharField(blank=True, max_length=200, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)])),
                ('tajweed_rules', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('excellent', 'ممتاز'), ('veryGood', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='halaqat.circle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='halaqat.student')),
            ],
        ),
        migrations.CreateModel(
            name='JuzTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('juz_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='رقم الجزء')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='الدرجة')),
                ('grade', models.CharField(choices=[('excellent', 'ممتاز'), ('veryGood', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول')], max_length=20)),
                ('tester_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='halaqat.circle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='halaqat.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'غائب بعذر'), ('late', 'متأخر'), ('unmarked', 'غير محضر')], default='unmarked', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الوصول')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة الحضور')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='halaqat.circle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='halaqat.student')),
            ],
            options={
                'indexes': [models.Index(fields=['circle', 'date'], name='halaqat_att_circle__0257d2_idx')],
                'unique_together': {('student', 'circle', 'date')},
            },
        ),
    ]
